apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: model-trainer
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: model-trainer
            image: $IMG_NAME
            imagePullPolicy: Always
            args:
            env:
            resources:
              limits:
                cpu: 500m
                memory: 4Gi
              requests:
                cpu: 50m
                memory: 512Mi
          restartPolicy: OnFailure