#config.yaml
hyperparameters:
  seed_val: 42
  optimizer_adam_lr: 2e-5
  optimizer_adam_eps: 1e-8
  epochs: 4
  learning_rate_warmups: 0
  loader_batch_size: 32
  train_size_percentage: 0.9
  sentence_max_length: 64
  learning_rate: 1e-4
  device: "gpu"
  use_wandb: True